# docker-compose.test.yml
# Define test dependencies: Postgres and Redis
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    # Optional health check: uncomment if pg_isready works reliably
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U test -d testdb"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    # Optional health check: uncomment if redis-cli is available
    # healthcheck:
    #   test: ["CMD-SHELL", "redis-cli ping"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
