name: build-test-release

on:
  push:
    branches: [ main ]
    tags:    [ 'v*.*.*' ]   # Tagging triggers the release step
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run pytest
      run: pytest -q

    - name: Build wheel
      run: python -m build --wheel --outdir dist

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: veltraxor-wheel
        path: dist/*.whl

  publish:
    # Only executed when tag (vX.Y.Z) is pushed to main
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: production   # Optional: GitHub environment

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Build & publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m pip install --upgrade pip build twine
        python -m build --wheel --outdir dist
        twine upload --non-interactive -u _token_ -p "$PYPI_TOKEN" dist/*

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build & push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/veltraxor:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/veltraxor:${{ github.ref_name }}