name: API Test (pytest + TestClient)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest          # Linux runner
    env:
      PYTHONUTF8: "1"
      VELTRAX_API_TOKEN: ${{ secrets.VELTRAX_API_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install runtime + dev/test deps
          pip install -e .[dev]
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # ensure these libs exist even if extras missed them
          pip install fastapi uvicorn httpx python-dotenv pydantic-settings jsonschema

      - name: Run pytest
        run: pytest -q
