name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - '5432:5432'
        options: >-
          --health-cmd="pg_isready -U test -d testdb"

      redis:
        image: redis:7
        ports:
          - '6379:6379'
        options: >-
          --health-cmd="redis-cli ping"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system tools
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-tools docker-compose-plugin

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Inject dummy env vars
        run: |
          echo "XAI_API_KEY=dummy"   >> $GITHUB_ENV
          echo "XAI_API_URL=http://localhost/dummy" >> $GITHUB_ENV
          echo "VELTRAX_API_TOKEN=dummy" >> $GITHUB_ENV

      - name: Run all tests
        env:
          PYTHONUTF8: '1'
        run: pytest test -q
