name: Component Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Debug Python setup
        shell: pwsh
        run: python --version || echo "Python not found"

      - name: Create virtual environment
        shell: pwsh
        run: python -m venv .venv

      - name: Activate venv & install front-end deps
        working-directory: Frontend
        shell: pwsh
        run: |
          & ${{ runner.workspace }}\.venv\Scripts\Activate.ps1
          npm install

      - name: Debug front-end env
        working-directory: Frontend
        shell: pwsh
        run: |
          & ${{ runner.workspace }}\.venv\Scripts\Activate.ps1
          node --version
          npm --version
          dir

      - name: Run tests
        working-directory: Frontend
        shell: pwsh
        run: |
          & ${{ runner.workspace }}\.venv\Scripts\Activate.ps1
          npm install
          npx vitest run \
            --root . \
            --include "**/*.{test,spec}.{js,ts,jsx,tsx}" \
            --passWithNoTests
