name: Fault Injection, DAST Scan & Synthetic Monitoring Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration:
    name: Backend Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.13.5" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install fakeredis pytest

      - name: Run Fault Injection suite
        run: python -m pytest test/integration/test_fault_injection.py

      - name: Run DAST Scan suite
        run: python -m pytest test/integration/test_dast_scan.py

      - name: Run Synthetic Monitoring suite
        run: python -m pytest test/integration/test_synthetic_alerting.py

      - name: Upload Integration Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-logs
          path: |
            **/pytest*.xml
