name: Fault Injection, DAST Scan & Synthetic Monitoring Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'test/integration/**'
      - '.github/workflows/fault-injection-dast-synthetic-monitoring.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'test/integration/**'

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: [3.13.5]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install fakeredis
    outputs:
      venv: .venv

  fault_injection:
    name: Fault Injection Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Activate venv
        run: source .venv/bin/activate
      - name: Run Fault Injection suite
        run: pytest test/integration/test_fault_injection.py

  dast_scan:
    name: DAST Scan Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Activate venv
        run: source .venv/bin/activate
      - name: Run DAST Scan suite
        run: pytest test/integration/test_dast_scan.py

  synthetic_monitoring:
    name: Synthetic Monitoring Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Activate venv
        run: source .venv/bin/activate
      - name: Run Synthetic Monitoring suite
        run: pytest test/integration/test_synthetic_alerting.py

  upload-artifacts:
    name: Upload Integration Test Results
    if: always()
    runs-on: ubuntu-latest
    needs: [fault_injection, dast_scan, synthetic_monitoring]
    steps:
      - name: Upload pytest logs
        uses: actions/upload-artifact@v3
        with:
          name: integration-logs
          path: |
            **/pytest*.xml
