name: JSON Schema Regression Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  contract-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Restore private core
        shell: pwsh
        run: |
          echo "${{ secrets.PRIVATE_CORE_ZIP_B64 }}" > core.b64
          base64 --decode core.b64 > PrivateCore.zip
          unzip -o PrivateCore.zip -d core
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'
      - name: Install dependencies
        shell: pwsh
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1
          pip install --upgrade pip setuptools
          pip install -r requirements.txt
      - name: Configure environment
        shell: pwsh
        run: |
          $Env:OPENAPI_SCHEMA_PATH = "${{ github.workspace }}\openapi_schema.json"
          $Env:API_BASE_URL        = "http://127.0.0.1:8000"
          $Env:CHATBOT_TOKEN       = "${{ secrets.CHATBOT_TOKEN }}"
      - name: Install service dependencies
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          pip install prometheus_client httpx fastapi
      - name: Launch API server
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          Start-Process -NoNewWindow -FilePath .\.venv\Scripts\uvicorn.exe -ArgumentList 'api_server:app','--host','127.0.0.1','--port','8000','--reload'
          Start-Sleep -Seconds 2
      - name: Enable stub mode
        shell: pwsh
        run: |
          $Env:COST_SAVING_TEST = "true"
          $Env:MOCK_LLM         = "true"
      - name: Check formatting with Black
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          black --check .
      - name: Run contract test
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest test/test_json_schema_regression.py -q
