name: Lint and Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project and dev dependencies
        run: |
          pip install -e .[dev]
          pip install mypy ruff black pytest requests types-requests types-setuptools jsonschema pydantic-settings

      - name: Run ruff lint
        run: ruff check .

      - name: Check Black formatting
        run: black --check .

      - name: Run mypy type check
        run: python -m mypy .

      - name: Run pytest
        run: pytest -q
