# .github/workflows/quick_verification.yml
name: Quick Verification

on:
  push:
    branches: [ deep-stress-test ]
  workflow_dispatch:

jobs:
  quick-verification:
    runs-on: windows-latest

    # 全局环境变量，跨 step 保持一致
    env:
      BASE_URL: "http://127.0.0.1:8000"
      VELTRAX_API_TOKEN: ${{ secrets.VELTRAX_API_TOKEN }}
      MOCK_LLM: "1"
      COST_SAVING_TEST: "1"
      API_TOKEN: ${{ secrets.VELTRAX_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Create venv & install dependencies
        shell: pwsh
        run: |
          python -m venv .venv --upgrade-deps
          .\.venv\Scripts\Activate.ps1
          pip install -r requirements.txt

      - name: Start mock server (background)
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          # 用 venv 中的 python 启动 uvicorn
          Start-Process -FilePath ".\.venv\Scripts\python.exe" `
                        -ArgumentList "-m","uvicorn","api_server:app","--host","127.0.0.1","--port","8000","--log-level","info" `
                        -NoNewWindow
          Start-Sleep -Seconds 10

      - name: Run quick cost-saving test
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          python .\test\deep_stress\deep_stress_test.py
