name: Secret Leak Scan
on:
  push:
    branches: [ main, deep-stress-test ]
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      # 默认 fetch-depth: 1
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--path=. --verbose"
