name: Secret Leak Scan

on:
  push:
    branches: [ main, deep-stress-test ]
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Restore private core
        run: |
          echo "${{ secrets.PRIVATE_CORE_ZIP_B64 }}" > core.b64
          base64 --decode core.b64 > PrivateCore.zip
          unzip -o PrivateCore.zip -d core
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          flags: "--path=. --verbose"
