name: Secret Leak Scan
on:
  push:
    branches: [ main, deep-stress-test ]
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      # Fetch the full Git history (by default only fetch-depth:1 will cause revision range parsing to fail)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          # v2 uses flags instead of args
          flags: "--path=. --verbose"
