name: Startup Robustness Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  startup-robustness:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create venv & install dependencies
        shell: pwsh
        run: |
          python -m venv .venv
          Set-Item -Path Env:VELTRAX_API_TOKEN -Value "${{ secrets.VELTRAX_API_TOKEN }}"
          .\.venv\Scripts\Activate.ps1
          pip install --upgrade pip
          pip install respx
          pip install -e .[dev]

      - name: Run startup robustness tests
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m pytest test/integration/test_startup_robustness.py -v

      - name: Run full test suite
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m pytest -q
