# .github/workflows/static_security_analysis.yml
name: Static Security Analysis

on:
  push:
    branches:
      - main
      - deep-stress-test
  pull_request:
    branches:
      - main
      - deep-stress-test

jobs:
  sast:
    name: Bandit SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit scan
        run: |
          bandit -r . --severity-level high --confidence-level high
