name: Frontend Unit Testing

on:
  push:
    branches:
      - 'Frontend Testing'
  pull_request:
    branches:
      - 'Frontend Testing'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          npm install
          npm install vitest --save-dev

      - name: Run tests
        run: |
          npm run test
