name: Frontend Unit Testing

on:
  push:
    branches:
      - 'frontend-testing'
  pull_request:
    branches:
      - 'frontend-testing'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install Node.js dependencies
        run: npm install

      - name: Run tests
        run: npm run test
